# Generated by Django 6.0.6 on 2026-10-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0005_invoice_customer_invoiceitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount on item in INR', max_digits=10),
        ),
    ]
